version: "3"
services:
  server:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    restart: always
    volumes:
#      - ./gotty:/webtty/gotty
#      - ./resources/index.html:/webtty/index.html
      - ../home:/home/student
    command: "/webtty/gotty -w --index /webtty/index.html  --ws-origin \".*\" bash"
    ports:
      - "8090:8080"
